version: '3'

services: 
  nodejs: 
    # 指定以当前目录下的Dockerfile文件打包成镜像
    build: 
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    ports: 
      - "8080:8080"
    # 本次新增的
    depends_on:
      - db
    networks: 
      - app-network

  # 连接数据库(本次新增的)
  db:
    image:  mongo:latest
    container_name: db
    restart: unless-stopped
    ports: 
      - "27017:27017"
    # environment: 
    #   - MYSQL_ROOT_PASSWORD=123456
    #   - MYSQL_USER=test1 # 创建一个test1的用户
    #   - MYSQL_PASSWORD=test1 # test1用户密码
    #   - MYSQL_DATABASE=nodeApp
    #   - TZ=Asia/Shanghai # 设置时区
    volumes: 
      - ./opt/mongodb/data:/data/db                                                                             

    # command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    # command: --default-authentication-plugin=mysql_native_password #这行代码解决无法访问的问题

    networks: 
      - app-network

networks:
  app-network:
    driver: bridge
